git_research_task:
  description: >
    Conduct a thorough research about Git repositories, commit history, trends in programming languages, and framework usage in open-source or private repositories.
    Make sure you find any interesting and relevant information given the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about Git repositories, including trends in commits, contributors, language usage, frameworks, and security aspects.
  agent: senior_git_data_researcher

git_reporting_task:
  description: >
    Review the context you got from the research and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information about Git repositories, their activities, commit patterns, and language trends.
    Formatted as markdown without '```'.
  agent: git_reporting_analyst
